### ISSUE TITLE
Reverting Your Commits

### ISSUE THREAD

**Issue by chrisdaaz** [chrisdaaz/branching#5]
Hi Anne!

Thanks for working on this lab. Here's some feedback on your commits:

As you can see from the [commit history](https://github.com/chrisdaaz/branching/commits/main), you made the correct changes to the repository (adding and editing the `metadata.csv` file), but all of these changes happened on the `main` branch. 

You don't need to redo the assignment, but I wanted to let you know that these changes should have happened on a **new** branch for _your_ edits called `mcmahon`, so the first steps in this lab would have looked like:

```bash
$ git clone git@github.com:chrisdaaz/branching.git
$ cd branching
$ git branch mcmahon
$ git checkout mcmahon
```

Once you're on the new branch, _then_ you can commit the changes to repository, such as adding the `metadata.csv` file and editing the titles, etc. With this workflow, team members can do their work and make commits without affecting the main project until the work is complete and has been reviewed and accepted by team members to be merged into the main project.

Anyways, hope that helps clarify things. Thanks again!

-Chris

**Comment by annabel-mc** [comment]
Thanks Chris, apologies, I think I went in and out of the terminal too many times, I was getting distracted, I thought I was in the branch mcmahon but obviously not!  I was getting an error message when i tried to push the branch, which was confusing me and I restarted a few times.  I am glad I wasn't working on a real project! Thanks again Anne
